// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCanK9O232d50ecvx9B6HGcHdjSLht6cI',
    appId: '1:92659577777:web:3e734735565e5493218390',
    messagingSenderId: '92659577777',
    projectId: 'catalift-8cf6e',
    authDomain: 'catalift-8cf6e.firebaseapp.com',
    storageBucket: 'catalift-8cf6e.firebasestorage.app',
    measurementId: 'G-H4NZBH8LW2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXxh8c4rtDwyPWaaJIyedVaioG_F4DbBc',
    appId: '1:92659577777:android:ec2e2b96dc58860f218390',
    messagingSenderId: '92659577777',
    projectId: 'catalift-8cf6e',
    storageBucket: 'catalift-8cf6e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtAfOuhDoDNsv7DUxFwtO6tbe5NtHziYA',
    appId: '1:92659577777:ios:01404e1c33db8825218390',
    messagingSenderId: '92659577777',
    projectId: 'catalift-8cf6e',
    storageBucket: 'catalift-8cf6e.firebasestorage.app',
    iosBundleId: 'com.example.cataliftAssignment',
  );
}
